import './global.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'OneTT',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className="dark:bg-gradient-to-l dark:from-slate-950 dark:to-blue-950 h-screen w-screen">
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
