import '../global.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'OneTT',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white dark:bg-gradient-to-l dark:from-slate-950 dark:to-blue-950 h-screen w-screen">
        <Navbar/>
        <div className="pt-16">
          {children}
        </div>
       
      </body>
    </html>
  )
}
